# 1 PageRank Formulation
Consider a directed graph G = (V, E):

with V = {1, 2, 3, 4, 5}, and E = {(1, 2),(1, 3),(2, 1),(2, 3),(3, 4),(3, 5),(4, 5),(5, 4)}.

## (a) 给出G的邻接矩阵，及对应的列随机矩阵M
Write down the adjacency matrix of graph G and its corresponding column
stochastic matrix M discussed in lecture.

In [1]:
E = {(1, 2),(1, 3),(2, 1),(2, 3),(3, 4),(3, 5),(4, 5),(5, 4)}
import numpy as np
# M0表示邻接矩阵,Mij 表示 j指向i
M0 = np.zeros(shape=(5,5),dtype=np.int)
for edge in E:
    M0[edge[1]-1,edge[0]-1]=1
    
M0

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0]])

In [2]:
# 每个节点的出度
outlinks = np.sum(M0,axis=0)#
outlinks

array([2, 2, 2, 1, 1])

In [3]:
# M表示列随机矩阵，Mij 表示 j指向i 时的转移概率
# 参考[Numpy：如何用向量元素除以每一行？](https://cloud.tencent.com/developer/ask/72998),此处用的是用向量元素除以每一列
M = M0/outlinks[None,:] 
M

array([[0. , 0.5, 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 1. ],
       [0. , 0. , 0.5, 1. , 0. ]])

## (b) 假设随机跳转概率(1-b)为0.2，写出计算G的pagerank的公式
Set up the equations to compute pagerank for G. Assume that the probability
of teleport is 0.2.

In [4]:
b = 0.8 # teleport is 0.2.
N = len(M0) # 节点的格式
r = np.ones(shape=(N,),dtype=np.float)/N # 初始化r = 1/N
r

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [5]:
e = 0.000001
for i in range(50):
    r_old = r[:]
#     print('r_old[:]=',r_old)
    # r = b * M*r + (1-b)/N 
    r=  b* np.dot(M,r) + (1-b)/N
    if np.sum(np.abs(r-r_old))<0.00001:
        print('sucess!')
        break
    print(i,',r=',r)
r

0 ,r= [0.12 0.12 0.2  0.28 0.28]
1 ,r= [0.088 0.088 0.136 0.344 0.344]
2 ,r= [0.0752 0.0752 0.1104 0.3696 0.3696]
3 ,r= [0.07008 0.07008 0.10016 0.37984 0.37984]
4 ,r= [0.068032 0.068032 0.096064 0.383936 0.383936]
5 ,r= [0.0672128 0.0672128 0.0944256 0.3855744 0.3855744]
6 ,r= [0.06688512 0.06688512 0.09377024 0.38622976 0.38622976]
7 ,r= [0.06675405 0.06675405 0.0935081  0.3864919  0.3864919 ]
8 ,r= [0.06670162 0.06670162 0.09340324 0.38659676 0.38659676]
9 ,r= [0.06668065 0.06668065 0.0933613  0.3866387  0.3866387 ]
10 ,r= [0.06667226 0.06667226 0.09334452 0.38665548 0.38665548]
11 ,r= [0.0666689  0.0666689  0.09333781 0.38666219 0.38666219]
12 ,r= [0.06666756 0.06666756 0.09333512 0.38666488 0.38666488]
sucess!


array([0.06666702, 0.06666702, 0.09333405, 0.38666595, 0.38666595])

## (c)  假设主题子集为{1,2},重新计算pagerank
Set up the equations for topic-specific pagerank for the same graph, with teleport
set {1, 2}. Solve the equations and compute the rank vector.

In [6]:
s=[1,2]
S = np.zeros(shape=(N,N),dtype=np.float)
for i in s:
    S[i-1,:]=1
S = S/len(s)
S

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ]])

In [7]:
A=b*M+(1-b)*S
A

array([[0.1, 0.5, 0.1, 0.1, 0.1],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.4, 0.4, 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0. , 0.8],
       [0. , 0. , 0.4, 0.8, 0. ]])

In [8]:
# 带有主题的pagerank计算方法
r = np.ones(shape=(N,),dtype=np.float)/N # 初始化r = 1/N
e = 0.000001
for i in range(50):
    r_old = r[:]
    r= np.dot(A,r)
    if np.sum(np.abs(r-r_old))<0.00001:
        print('sucess!')
        break
    print(i,',r=',r,r.sum())

0 ,r= [0.18 0.18 0.16 0.24 0.24] 1.0
1 ,r= [0.172 0.172 0.144 0.256 0.256] 1.0
2 ,r= [0.1688 0.1688 0.1376 0.2624 0.2624] 1.0
3 ,r= [0.16752 0.16752 0.13504 0.26496 0.26496] 1.0000000000000002
4 ,r= [0.167008 0.167008 0.134016 0.265984 0.265984] 1.0000000000000002
5 ,r= [0.1668032 0.1668032 0.1336064 0.2663936 0.2663936] 1.0000000000000004
6 ,r= [0.16672128 0.16672128 0.13344256 0.26655744 0.26655744] 1.0000000000000004
7 ,r= [0.16668851 0.16668851 0.13337702 0.26662298 0.26662298] 1.0000000000000002
8 ,r= [0.1666754  0.1666754  0.13335081 0.26664919 0.26664919] 1.0000000000000004
9 ,r= [0.16667016 0.16667016 0.13334032 0.26665968 0.26665968] 1.0000000000000002
10 ,r= [0.16666806 0.16666806 0.13333613 0.26666387 0.26666387] 1.0000000000000002
sucess!


## (d) 给出5对（S，v）的示例，其中S⊆V和v∈V，v对于子集S的pagerank为0。解释原因
Give 5 examples of pairs (S, v), where S ⊆ V and v ∈ V , such that the topic specific pagerank of v for the teleport set S is equal to 0. Explain why these values are equal to 0.



所有的有向图都可以看做由强连通分量组成的DAG图

![x](./image/GML_HW2_SSC_DAG.jpg)

根据spider trap 和dead end的样例，若v对于子集S的pagerank为0,则S作为强联通分量到v节点(或v节点所在的强连通分量)没有路径，存在如下样例

- S={4,5},v=3
- S={4,5},v=1
- S={4,5},v=2
- S={3,4,5},v=2
- S={3,4,5},v=1

# 2 Dead ends in PageRank computation
Let the matrix of the Web M be an n-by-n matrix, where n is the number of
Web pages. The entry $m_{ij}$ in row i and column j is 0, unless there is an arc
from node (page) j to node i. In that case, the value of $m_{ij}$ is $\frac{1}{k}$
, where k is the
number of arcs (links) out of node j. Notice that if node j has k > 0 arcs out,
then column j has k values of $\frac{1}{k}$
and the rest 0’s. If node j is a dead end (i.e.,
it has zero arcs out), then column j is all 0’s.

Let $r = [r_1, r_2, ..., r_n]^T$ be (an estimate of) the PageRank vector; that is, $r_i$
is the estimate of the PageRank of node i. Define $\boldsymbol{r}$ to be the sum of the
components of $\boldsymbol{r}$; that is $w(\boldsymbol{r}) = \sum_{i=1}^{n}{r_i}$.

In one iteration of the PageRank algorithm, we compute the next estimate
$r'$ of the PageRank as: $r'  = M\boldsymbol{r}$. Specifically, for each i we compute 
$r_i' = \sum_{j=1}^{n}{M_{ij}r_j}$ . Define $w(r')$  to be the sum of components of r; that is
$w(r') = \sum_{i=1}^{n}{r’_i}$
. You may use D (the set of dead nodes) in your equation.

## (a)
Suppose the Web has no dead ends. Prove that $w(r') = w(r)$.

**证明过程如下:**

已知：

$$ r_i' = \sum_{j=1}^{n}{M_{ij}r_j} $$

同时根据列随机矩阵M的定义，可以得出：
$$ \sum_{i=1}^{n}{M_{ij}} = 1   $$ 

则

$$ \begin{aligned}
w(r') &= \sum_{i=1}^{n}{r'_i}  \\
&= \sum_{i=1}^{n} \sum_{j=1}^{n}{M_{ij}r_j} \\
&= \sum_{j=1}^{n} \sum_{i=1}^{n} {M_{ij}r_j} \\
&= \sum_{j=1}^{n}r_j  \\
& = w(r) \\ 
\end{aligned}$$  

## (b)
Suppose there are still no dead ends, but we use a teleport probability of 1-
β, where 0 < β < 1. The expression for the next estimate of $r_i$  becomes
$$r_i' = \beta\sum_{j=1}^{n}{M_{ij}r_j}+\frac{(1-\beta)}{n}$$
Under what circumstances will $w(r') = w(r)$.?
Prove your conclusion.


**证明过程如下:**

已知： $$r_i' = \beta \sum_{j=1}^{n}{M_{ij}r_j} + \frac {(1- \beta)}{n} $$

则

$$ 
\begin{aligned}
w(r') &= \sum_{i=1}^{n}{r'_i} \\
&= \sum_{i=1}^{n} \left(\beta \sum_{j=1}^{n}{M_{ij}r_j} + \frac {(1- \beta)}{n} \right) \\
&= \beta \sum_{i=1}^{n} \sum_{j=1}^{n}{M_{ij}r_j} + \sum_{i=1}^{n} \frac {(1- \beta)}{n}  \\
&= \beta w(r)  + (1- \beta) 
\end{aligned}
$$ 

如果 $w(r') = w(r)$ 等式成立，带入上面式子得：

$$ 
\begin{aligned}
w(r) &= \beta w(r)  + (1- \beta)  \\
w(r) &=1 
\end{aligned}
$$

## (c)
Now, let us assume a teleportation probability of 1-β in addition to the fact that
there are one or more dead ends. Call a node dead if it is a dead end and live if
not. Assume w(r) = 1. At each iteration, each live node j distributes $(1-\beta)\frac {r_j}{n}$
PageRank to each of the other nodes, and each dead node j distributes $\frac {r_j}{n}$
PageRank to each of the other nodes.
Write the equation for $r'_i$
in terms of β, M, r, n, andD (where D is the set of
dead nodes). Then, prove that w(r') is also 1.

**证明过程如下:**

$r'_i$的表达式如下：

$$r_i' = \beta \sum_{j=1}^{j\not\in D}{M_{ij}r_j} + \sum_{j=1}^{j\not\in D}(1-\beta)\frac {r_j}{n} +  \sum_{j=1}^{j\in D}\frac {r_j}{n}$$


同时根据列随机矩阵M的定义，可以得出：
$$ \sum_{i=1}^{n}{M_{ij}} = 1   $$ 

则w(r') 的证明如下：

$$ 
\begin{aligned}
w(r') &= \sum_{i=1}^{n}{r'_i} \\
&= \sum_{i=1}^{n} \left( \beta \sum_{j=1}^{j\not\in D}{M_{ij}r_j} + \sum_{j=1}^{j\not\in D}(1-\beta)\frac {r_j}{n} +  \sum_{j=1}^{j\in D}\frac {r_j}{n} \right) \\
&= \beta \sum_{i=1}^{n} \sum_{j=1}^{j\not\in D}{M_{ij}r_j} + (1-\beta)\sum_{i=1}^{n} \sum_{j=1}^{j\not\in D}\frac {r_j}{n} +  \sum_{i=1}^{n} \sum_{j=1}^{j\in D}\frac {r_j}{n}  \\
&= \beta \sum_{j=1}^{j\not\in D}\sum_{i=1}^{n} {M_{ij}r_j} + (1-\beta) \sum_{j=1}^{j\not\in D}\sum_{i=1}^{n} \frac {r_j}{n} + \sum_{j=1}^{j\in D}\sum_{i=1}^{n} \frac {r_j}{n}   \\
&= \beta \sum_{j=1}^{j\not\in D}r_j + (1-\beta) \sum_{j=1}^{j\not\in D}  {r_j} + \sum_{j=1}^{j\in D}{r_j}  \\
&= \sum_{j=1}^{j\not\in D}r_j + \sum_{j=1}^{j\in D}{r_j}  \\
&= \sum_{j=1}r_j \\
&= w(r) \\
&= 1  \\
\end{aligned}
$$ 